#!/bin/bash
#
# Starts the Sahara Rig Client.
#
# description: rigclient
# processname: rigclient
#
# author: tmachet (tania.machet@eng.uts.edu.au)
# date: 12/03/2010

INST_DIR=/usr/local/rigclient
test -d $INST_DIR || exit 0

# Executables
EXEC=rigclientservice

RETVAL=0

start() {
    PID=`ps -C $EXEC | grep rigclient | awk -F ' ' '{prinf $1}' `
    if [[ ! "$PID" > 0 ]]; then
		echo "Starting the Rig Client..."
		pushd .
		cd $INST_DIR
		$INST_DIR/$EXEC &
		popd
	lse
		echo "Rig Client has already started. Process ID "$PID
    fi
}

stop() {
    PID=`ps -C $EXEC | grep rigclient | awk -F ' ' '{prinf $1}' `
    if [[ "$PID" > 0 ]]; then
    	echo "Shutting down rigclient with PID "$PID"..."
		kill -SIGTERM $PID &> /dev/null
    fi
}


restart() {
    echo "Restarting rigclient..."
    stop
    sleep 5
    start
}	

reload() {
	restart
}	


case "$1" in
start)
	start
	;;
stop)
	stop
	;;
reload|restart)
	restart
	;;
*)
	echo $"Usage: $0 {start|stop|restart}"
	exit 1
esac

exit $?


