#!/bin/bash
#
# Starts the Sahara Rig Client.
#
# description: rigclient
# processname: rigclient
#
# author: tmachet (tania.machet@eng.uts.edu.au)
# date: 12/03/2010
#
# chkconfig: 345 95 5
# description: Rig Client service for Sahara rig client


INST_DIR=/usr/lib/rigclient
test -d $INST_DIR || exit 0

# Executables
EXEC=rigclientservice

RETVAL=0

start() {
	# Check whether user is root in order to stop or start tasks
	if [[ `id - u` != 0 ]] ; then
		echo "Only root may start the rig client"
		return
	fi 
    PID=`ps -C $EXEC | grep rigclient | awk -F' ' '{ printf $1 }' `
    if [[ ! "$PID" > 0 ]]; then
		echo "Starting the Rig Client..."
		pushd .
		cd $INST_DIR
		$INST_DIR/$EXEC &> /dev/null &
		popd
	else
		echo "Rig Client has already started. Process ID "$PID
    fi
}

stop() {
	# Check whether user is root in order to stop or start tasks
	if [[ `id - u` != 0 ]] ; then
		echo "Only root may stop the rig client"
		return
	fi 
    PID=`ps -C $EXEC | grep rigclient | awk -F' ' '{ printf $1 }' `
    if [[ "$PID" > 0 ]]; then
    	echo "Shutting down rigclient with PID "$PID"..."
		kill -SIGTERM $PID &> /dev/null
	else
		echo "No Rig Client found to shut down"
    fi
}


restart() {
	# Check whether user is root in order to stop or start tasks
	if [[ `id - u` != 0 ]] ; then
		echo "Only root may restart the rig client"
		return
	fi 
    echo "Restarting rigclient..."
    stop
    sleep 10
    start
}	

reload() {
	restart
}	

status() {
    PID=`ps -C $EXEC | grep rigclient | awk -F' ' '{ printf $1 }' `
    if [[ ! "$PID" > 0 ]]; then
		echo "Rig Client is running.  PID is "$PID"."
	else
		echo "Rig Client is not running."
	fi
}


case "$1" in
start)
	start
	;;
stop)
	stop
	;;
reload|restart)
	restart
	;;
status)
	status
	;;
*)
	echo $"Usage: $0 {start|stop|restart|status}"
	exit 1
esac

exit $?


